runtime: nodejs20
env: standard

env_variables:
  NODE_ENV: production
  PORT: 8080

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  min_idle_instances: 0

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
